<main class="container thanks_order">

  <h2><i class="fa fa-exclamation-triangle" aria-hidden="true"></i> Erreur 404 ! Page introuvable !</h2>
  <article class="center">
    <img src="<?php echo $domain;?>assets/img/error_404.jpg" alt="error_404">
    <p>Il se peut qu'elle ait été déplacée dans une autre rubrique ou tout simplement supprimée du site !</p>
    <p><a class="return_404" href="<?php echo $domain;?>">Retour à la page d'accueil</a></p>
  </article>
</main>
