<div class="div_create_post">

	<a href="<?php echo $domain;?>realisations" class="cta retour"><i class="fa fa-reply" aria-hidden="true"></i> Retour</a>
	<main class="container realisations main_admin_post">

		<h2>Ajouter un Article</h2>
		<form method="POST" action="" class="form" id="create_post" enctype="multipart/form-data">

			<!--
			enctype ==> indique le type d'encodage des données.
			Elle prendra la valeur « multipart/form-data »,
			qui spécifie que le formulaire envoie des données binaires (fichier)
			et du texte (champs de formulaire).
		-->

		<fieldset>
			<legend></legend>
			<input type="hidden" name="session" id="session" value=<?= $_SESSION['id'] ?> />

			<p class="flex">
				<label for="title">Titre :</label>
				<input type="text" placeholder="Titre" id="title_add_post" name="title" required>
			</p>
			<p class="flex">
				<label for="description">Description / Réalisation :<br>
					<em>(séparer les 2 parties par : '/////')</em></label>
					<textarea placeholder="Description" id="description_add_post" name="description"></textarea>
				</p>

				<p class="flex">
					<label for="ingredients">Ingrédients :<br>
						<em>(séparer chaque ingrédient par un tiret '-')</em></label>
						<textarea placeholder="Ingredients" id="ingredients_add_post" name="ingredients"></textarea>
					</p>

					<!-- CHOIX DE LA CATEGORIE -->

					<div class="flex div_primary_category">
						<p class="category_post">Catégorie :</p>

						<div class="div_category">
							<p>
								<input type="radio" id="realisations" name="category" value="realisations" checked>
								<label for="realisations">Mes Réalisations</label>
							</p>
							<p>
								<input type="radio" id="prestations" name="category" value="prestations">
								<label for="prestations">Mes Prestations</label>
							</p>
							<p>
								<input type="radio" id="autre" name="category" value="autre">
								<label for="autre">Autre</label>
							</p>
						</div>
					</div>

					<!-- CHOIX DU/DES MATERIELS -->

					<div class="flex div_primary_material">
						<p class="material_post">Matériel(s) nécessaire(s) :</p>

						<div class="div_material">
							<p>
								<input type="checkbox" id="material_shaker" name="material_shaker">
								<label for="material_shaker">Shaker</label>
							</p>
							<p>
								<input type="checkbox" id="material_verreamelange" name="material_verreamelange">
								<label for="material_verreamelange">Verre à Mélange</label>
							</p>
							<p>
								<input type="checkbox" id="material_cuillereamelange" name="material_cuillereamelange">
								<label for="material_cuillereamelange">Cuillère à Mélange</label>
							</p>
							<p>
								<input type="checkbox" id="material_pilon" name="material_pilon">
								<label for="material_pilon">Pilon</label>
							</p>
							<p>
								<input type="checkbox" id="material_blender" name="material_blender">
								<label for="material_blender">Blender</label>
							</p>
						</div>
					</div>

					<input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
					<!-- 1 Mo = 2^20 octets = 1048576 octets -->
					<p class="flex">
						<label for="picture">Uploader une image : <br><em>(JPG, PNG ou GIF - Max. 1 Mo)</em></label>
						<input type="file" id="picture_add_post" name="picture">
					</p>

				</fieldset>
				<!-- <input type="hidden" name="value_input_submit" value="envoyer"/> -->
				<input type="submit" value=" Créer un Article" class="cta input_creation_post" id="creation_create_post" name="envoyer">
			</form>

		</main>

	</div>
