<?php
if(!isset($_SESSION['id']) || $_SESSION['status'] != 5){ echo "<script type='text/javascript'>document.location.replace('index.php');</script>";}
else{
?>
<main class="container prestations main_prestations">

  <a href="<?php echo $domain;?>admin" class="cta retour"><i class="fa fa-reply" aria-hidden="true"></i> Retour</a>

  <h2><i class="fa fa-list-ul" aria-hidden="true"></i> Liste des Images</h2>
  <section class="section_admin">

    <table class="tab_list_pictures">

      <thead>
        <tr>
          <th>Id</th>
          <th class="td_short">Titre</th>
          <th>Source</th>
          <th>Id Post</th>
          <th>Titre Post</th>
          <th>Date</th>
          <th>Id User</th>
          <th>Pseudo User</th>
        </tr>
      </thead>

      <tbody>
        <?php
        foreach($aList_Pictures as $aIndex => $aCol){ ?>
          <tr>
            <?php
            foreach ($aCol as $key => $sValue) {
              if($key == "picture_id" ||
              $key == "picture_titre" ||
              $key == "picture_source" ||
              $key == "picture_id_post" ||
              $key == "post_titre" ||
              $key == "date" ||
              $key == "post_id_user" ||
              $key == "user_pseudo")
              {
                if($key == "picture_source")
                {
                  ?>
                    <td class="td_picture"><img src='<?php echo $domain;?>pictures/<?= $sValue ?>' alt="<?= $sValue ?>"</td>
                    <?php
                }
                else if($key == "picture_titre")
                {
                  ?>
                    <td class="td_short"><?= $sValue ?></td>
                    <?php
                }
                else
                { ?>
                <td><?= $sValue ?></td>
                <?php
              }
            }
          } ?>
            </tr>
            <?php } ?>

          </tbody>
          <tfooter>
          </tfooter>
        </table>
      </section>

    </main>
<?php } ?>
