<main class="container prestations">

  <a href="<?php echo $domain;?>prestations" class="cta retour"><i class="fa fa-reply" aria-hidden="true"></i> Retour</a>

  <h2><i class="fa fa-birthday-cake" aria-hidden="true"></i> FÊTER UN EVENEMENT</h2>
  <section class="section_prestations_details">

    <img src="<?php echo $domain;?>assets/img/party_cocktails5.jpg" alt="party_cocktails5">
    <img src="<?php echo $domain;?>assets/img/party_cocktails4.jpg" alt="party_cocktails4">
    <img src="<?php echo $domain;?>assets/img/party_cocktails6.jpg" alt="party_cocktails6">

    <p>Vous souhaitez organiser un événement ?</p>
    <p>Mariage, soirée privée, vernissage, crémaillère,
      gala, soirée en amoureux, enterrement de vie de jeune fille, anniversaire,...
      Je m'adapte à votre thème: Noël, Halloween, St Valentin,...</p>
      <br>
      <p>Je me déplace chez vous avec mon matériel et tous les produits nécessaires pour transformer votre salon en véritable bar !</p>

      <p>Animations autour du bar, cocktails de fumée, tout est là pour créer une ambiance festive et conviviale.</p>
      <br>
      <p>Mes services vous permettent de profiter pleinement de vos invités.
        Je vous garantis des cocktails frais et délicieux qui
        impressionneront tous les participants.
        Que ce soit pour une petite ou une grande soirée, je vous propose un service personnalisé
        vous épargnant tout stress !</p>
        <br>

        <h4>Me contacter directement pour toute réservation de ce type</h4>

    <img src="<?php echo $domain;?>assets/img/party_cocktails.jpg" alt="party_cocktails">
    <img src="<?php echo $domain;?>assets/img/party_cocktails3.jpg" alt="party_cocktails3">

      </section>

      <div class="div_inscription">
        <p>Pour vous inscrire, c'est simple :</p>
        <ul class="prestations_inscription">
          <li><i class="fa fa-laptop" aria-hidden="true"></i><span> par internet : </span>remplissez le formulaire dans : <a class="a_contact" href="<?php echo $domain;?>contact">"Contact / Réservation"</a></li>
          <li><i class="fa fa-mobile" aria-hidden="true"></i> par téléphone : au <a class="tel_contact2" href="tel:+33682062629">06 82 06 26 29</a></li>
        </ul>
      </div>

    </main>
