<div class="div_create_account">
	<main class="container realisations main_prestations main_reset_password">

		<h2>Réinitialisation du Mot de Passe</h2>
		<div class="p_reset">
			<p>Vous avez perdu votre mot de passe ?</p>
			<p>Complétez les informations suivantes. Un nouveau mot de passe vous sera envoyé par e-mail.</p>
		</div>
		<form class="form" id="reset_password" method="POST" action="">
			<fieldset>
				<p class="flex">
					<label for="pseudo">Pseudo : </label>
					<input type="text" placeholder="Pseudo" id="pseudo_reset_password" name="pseudo" required>
				</p>
				<p class="flex">
					<label for="mail_user">Adresse Mail : </label>
					<input type="text" placeholder="Adresse Mail" id="mail_reset_password" name="mail_user" required>
				</p>
			</fieldset>
			<input type="submit" value=" Continuer" class="cta reset_password" id="reset_reset_password" name="reset_password">
		</form>

	</main>
</div>
